version: "3.9"
services:
  frontend:
    container_name: ${FRONTEND_CONTAINER_NAME}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    # depends_on:
    #   - backend
    volumes: # ローカルとコンテナのパスをマウント
      - ./frontend:/frontend
      - /etc/localtime:/etc/localtime:ro # タイムゾーンを日本時刻に設定
    working_dir: /frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_CONTAINER_PORT}
    security_opt:
      - seccomp:unconfined
    # environment:
    # - NEXT_PUBLIC_FIREBASE_API_KEY=${FIREBASE_API_KEY}
    # - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMINE}
    # - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
    # - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
    # - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
    # - NEXT_PUBLIC_FIREBASE_APP_ID=${FIREBASE_APP_ID}
    # - NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${FIREBASE_MEASUREMENT_ID}

  backend:
    container_name: ${BACKEND_CONTAINER_NAME}
    build: backend
    tty: true
    stdin_open: true
    depends_on:
      - db
    volumes: # ローカルとコンテナのパスをマウント
      - ./backend:/backend
      - /etc/localtime:/etc/localtime:ro # タイムゾーンを日本時刻に設定
    #      - $HOME/.aws/:/root/.aws/ # localのaws credential情報をコンテナにコピー (ローカルのaws情報を参照する場合)
    working_dir: /backend
    command: air -c .air.toml
    ports:
      - ${BACKEND_PORT}:${BACKEND_CONTAINER_PORT}
    security_opt:
      - seccomp:unconfined
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - BACKEND_CONTAINER_NAME=${BACKEND_CONTAINER_NAME}
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_CONTAINER_PORT=${BACKEND_CONTAINER_PORT}
      # - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      # - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      # - AWS_CREDENTIAL_USER=${AWS_CREDENTIAL_USER}
      # - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      # - AWS_S3_REGION=${AWS_S3_REGION}
      # - AWS_CLOUD_FRONT_URL=${AWS_CLOUD_FRONT_URL}
      # - JWT_KEY=${JWT_KEY}
      # - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      # - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      # - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      # - GOOGLE_CREDENTIALS_JSON=${GOOGLE_CREDENTIALS_JSON}
      - "TZ=Asia/Tokyo" # タイムゾーンを日本時刻に設定

  db:
    container_name: ${POSTGRES_HOST}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - "TZ=Asia/Tokyo" # タイムゾーンを日本時刻に設定
    image: postgres:14.2
    volumes:
      - cloud-run-sample-data:/var/lib/postgresql/data:delegated
      - ./db:/docker-entrypoint-initdb.d #初期データ
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_CONTAINER_PORT}

volumes:
  cloud-run-sample-data:
